# Generated by Django 2.1.3 on 2018-11-24 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import edeliver.models


class Migration(migrations.Migration):

    dependencies = [
        ('edeliver', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('document', models.FileField(upload_to=edeliver.models.upload_file_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
